[package]
name = "phantasy-init"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre.workspace = true
eyre.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true
dotenvy.workspace = true
